FROM node:13.8.0-alpine3.11

# change working directory to the app directory
WORKDIR /app

RUN npm install nodemon -g

COPY package*.json ./

# install npm
RUN npm install -qy

# copy all files in current directory to working directory
COPY . .

# expose Port to network
EXPOSE 8000

# run on
CMD [ "nodemon", "server.js" ]